# Generated by Django 4.2 on 2023-06-15 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("app", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="first_name", new_name="name"
        ),
        migrations.RemoveField(model_name="user", name="last_name"),
        migrations.CreateModel(
            name="Profession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "box",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subs",
                        to="app.profession",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userstories",
            name="professions",
            field=models.ManyToManyField(
                related_name="in_stories", to="app.profession"
            ),
        ),
    ]
