# Generated by Django 4.2 on 2023-06-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0003_user_uwhatsapp_user_whatsapp")]

    operations = [
        migrations.AlterField(
            model_name="geoxdetails",
            name="value",
            field=models.TextField(blank=True, default="", null=True),
        )
    ]
