# Generated by Django 4.2 on 2023-06-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0004_alter_geoxdetails_value")]

    operations = [
        migrations.RemoveField(model_name="userstories", name="a_interest"),
        migrations.RemoveField(model_name="userstories", name="needed_p"),
        migrations.AddField(
            model_name="userstories",
            name="wmen_per",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
