# Generated by Django 4.2 on 2023-06-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_campaign_mediapost_userstories_price_post_company_and_more")
    ]

    operations = [
        migrations.RemoveField(model_name="acceptedpost", name="checked"),
        migrations.AddField(
            model_name="acceptedpost",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="acceptedpost",
            name="result",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="acceptedpost",
            name="status",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
