# Generated by Django 4.2 on 2023-06-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0008_momocompte_payment_userstories_momo")]

    operations = [
        migrations.AddField(
            model_name="userstories",
            name="is_actif",
            field=models.BooleanField(default=False),
        )
    ]
