# Generated by Django 4.2 on 2023-06-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0009_userstories_is_actif")]

    operations = [
        migrations.AlterField(
            model_name="userstories",
            name="is_actif",
            field=models.BooleanField(default=True),
        )
    ]
