# Generated by Django 4.2 on 2023-06-28 09:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("app", "0010_alter_userstories_is_actif")]

    operations = [
        migrations.RemoveField(model_name="campaign", name="already_used"),
        migrations.RemoveField(model_name="campaign", name="total_invest"),
        migrations.AddField(
            model_name="post", name="already_used", field=models.IntegerField(default=0)
        ),
        migrations.AddField(
            model_name="post", name="clicks", field=models.IntegerField(default=0)
        ),
        migrations.AddField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="post", name="total_invest", field=models.IntegerField(default=0)
        ),
        migrations.CreateModel(
            name="Audiences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("point", models.IntegerField(default=0)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audiences",
                        to="app.campaign",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audiences_in",
                        to="app.userstories",
                    ),
                ),
            ],
        ),
    ]
