# Generated by Django 4.2 on 2023-06-28 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("app", "0011_remove_campaign_already_used_and_more")]

    operations = [
        migrations.AddField(
            model_name="post",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="app.company",
            ),
        )
    ]
