# Generated by Django 4.2 on 2023-07-02 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("app", "0012_post_company")]

    operations = [
        migrations.RemoveField(model_name="userstories", name="price"),
        migrations.AddField(
            model_name="acceptedpost", name="payc", field=models.IntegerField(default=0)
        ),
        migrations.AddField(
            model_name="campaign",
            name="name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="real_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaignes",
                to="app.company",
            ),
        ),
    ]
