# Generated by Django 4.2 on 2023-07-04 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("app", "0013_remove_userstories_price_acceptedpost_payc_and_more")]

    operations = [
        migrations.AddField(
            model_name="company",
            name="status",
            field=models.CharField(default="on", max_length=150),
        ),
        migrations.AddField(
            model_name="post",
            name="already_payed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="click_ips",
            field=models.TextField(blank=True, default="[]", null=True),
        ),
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.TextField(blank=True, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                ("typ", models.CharField(blank=True, max_length=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("action_url", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifs",
                        to="app.company",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifs",
                        to="app.userstories",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyPay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("amount", models.IntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pays",
                        to="app.company",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pays",
                        to="app.post",
                    ),
                ),
            ],
        ),
    ]
