# Generated by Django 4.2 on 2023-07-14 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_company_status_post_already_payed_post_click_ips_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.acceptedpost",
            ),
        )
    ]
