# Generated by Django 4.2 on 2023-07-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0015_alter_payment_post")]

    operations = [
        migrations.AddField(
            model_name="userstories",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        )
    ]
