# Generated by Django 4.2 on 2023-07-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0017_ciblef")]

    operations = [
        migrations.AddField(
            model_name="ciblef",
            name="quart",
            field=models.TextField(blank=True, null=True),
        )
    ]
